[package]
name = "ventura"
description = "A top down survival game written with bevy."
authors = ["abstraq <contact@abstraq.dev>"]
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.2.1"
bevy = { version = "0.15.3", features = ["wayland"] }
leafwing-input-manager = "0.16.0"
